library(readxl)
Data <- read_excel("C:/Users/USER/Desktop/Model2_data.xlsx")
attach(Data)

Model2 <- lm(PAY ~ G_N3_BUY_BUTTOM50_CNT_CNT +
	G_N3_BUY_TOP5_CNT_CNT +
	G_N3_BUY_BUTTOM50_CNT_OR_NOT +
	G_N3_BUY_TOP5_CNT_OR_NOT +
	G_N3_BUY_LIVE_STREAM_OR_NOT +
	G_N3_BUY_DATE_APP_OR_NOT +
	G_N3_BUY_GAME_APP_OR_NOT +
	G_N3_BUY_BUTTOM50_CNT_AVG_AMT +
	G_N3_BUY_TOP5_CNT_AVG_AMT +
	G_N3_BUY_BUTTOM50_DCON_OR_NOT +
	G_N3_BUY_BUTTOM50_AVG_PRICE_OR_NOT +
	G_N3_BUY_TOP5_DCON_OR_NOT +
	G_N3_BUY_TOP5_AVG_PRICE_OR_NOT +
	N3_NORM_TIME_CNT_PER_MONTH)

summary(Model2)

Model2-1 <- lm(PAY ~ G_N3_BUY_BUTTOM50_CNT_CNT +
	G_N3_BUY_TOP5_CNT_CNT +
	G_N3_BUY_BUTTOM50_CNT_OR_NOT +
	G_N3_BUY_TOP5_CNT_OR_NOT +
	G_N3_BUY_GAME_APP_OR_NOT +
	G_N3_BUY_BUTTOM50_CNT_AVG_AMT +
	G_N3_BUY_TOP5_CNT_AVG_AMT +
	G_N3_BUY_BUTTOM50_DCON_OR_NOT +
	G_N3_BUY_BUTTOM50_AVG_PRICE_OR_NOT +
	G_N3_BUY_TOP5_DCON_OR_NOT +
	G_N3_BUY_TOP5_AVG_PRICE_OR_NOT+
	N3_NORM_TIME_CNT_PER_MONTH)

summary(Model2-1)

